// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SavedPlan {
    "id": string;
    "name": string;
    "updatedAt": string;
    "state": { [_ in string]?: any } | null;
}
