// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeletePlan(id: string): $CancellablePromise<void> {
    return $Call.ByID(1854897626, id);
}

export function ListPlans(): $CancellablePromise<$models.SavedPlan[] | null> {
    return $Call.ByID(4198950226);
}

export function SavePlan(name: string, state: { [_ in string]?: any } | null): $CancellablePromise<$models.SavedPlan> {
    return $Call.ByID(3744279672, name, state);
}
